extraction:
  cpp:
    prepare:
      packages:
      - "build-essential"
      - "cmake"
    configure:
      command:
      - "mkdir build"
      - "cd build"
      - "cmake .. -DBUILD_PARSERS=OFF -DBUILD_CLIENT_GG=OFF"
    before_index: "export BOOST_DIR=$LGTM_SRC/boost"
    index:
      build_command:
      - "cd build"
      - "cmake --build . --config Release"
  python:
    python_setup:
      version: "3"