#!/bin/sh

set -e

ROOT=/usr/share/games/freeorion
cd ${ROOT}
printf 'CWD: '
pwd

DATAPATH="--resource-dir /usr/share/games/freeorion/default"

LD_LIBRARY_PATH="/usr/lib/freeorion:${LD_LIBRARY_PATH}" \
/usr/lib/freeorion/freeorion ${DATAPATH} "$@"
