name: "Snapcraft"

on:
  workflow_call:
    inputs:
      weekly-deploy:
        type: boolean
        default: false
    outputs:
      snap:
        description: "Snap file"
        value: ${{ jobs.snapcraft.outputs.snap }}

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build snap package
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Install built snap package
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    - name: Install dependencies for test launch
      run: |
        sudo apt update -y
        sudo apt install -y mesa-utils libgl1-mesa-dri libglx-mesa0
    - name: Test freeorion launch
      uses: coactions/setup-xvfb@v1
      with:
        run: /bin/bash .github/snap-xvfb-launch.sh
    - name: Upload binaries artifacts
      uses: actions/upload-artifact@v4
      if: ${{ inputs.weekly-deploy }}
      with:
        name: weekly-artifacts-snap-${{ github.run_number }}
        path: ${{ steps.snapcraft.outputs.snap }}
        if-no-files-found: error
        retention-days: 1

