name: "Build master"
on:
  push:
    branches:
      - ci-weekly-exp-macos
jobs:
  macos:
    strategy:
      matrix:
        os: [ macos-13 ]
    uses: ./.github/workflows/_build-macos.yml
    with:
      os: ${{ matrix.os }}
      weekly-deploy: true
