name: "Build master"
on:
  push:
    branches:
      - master
      - 'release-v*'
jobs:
  android:
    uses: ./.github/workflows/_build-android.yml
  android-godot4:
    uses: ./.github/workflows/_build-android-godot4.yml
