name: "Weekly Scheduled"
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  check-run:
    name: Check If Weekly Test Build should be built
    if: ${{ env.ENABLED_WEEKLY != 0 }}
    runs-on: ubuntu-latest
    steps:
      - name: Get previous builds info
        shell: bash
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          WORKFLOW_ID=$(gh api -X GET /repos/${{ github.repository }}/actions/runs/${{ github.run_id }} --jq='.workflow_id')
          TOTAL_COUNT=$(gh api -X GET "/repos/${{ github.repository }}/actions/workflows/${WORKFLOW_ID}/runs?status=success&per_page=1&head_sha=${{ github.sha }}" --jq '.total_count')
          echo "Total count: ${TOTAL_COUNT}"
