name: "PPA Godot"

on:
  push:
    tags:
      - ppa-godot-*

jobs:
  build-ubuntu:
    name: Upload PPA Godot
    runs-on: ubuntu-20.04
    env:
      super_secret_password=${{ secrets.super_secret_password }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: build-ubuntu-install-cache-id
        with:
          path: ${{ runner.temp }}/cache-build-linux-install
          key: build-ubuntu-20.04-install-cache-key-v1.0-ppa
      - uses: airvzxf/cache-anything-new-action@v1.0
        with:
          script: 'ubuntu-20.04-install-build.sh'
          is_cached: ${{ steps.build-ubuntu-install-cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-build-linux-install
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'
      - name: Prepare
      - run: |
          bash .ci/before_script.sh
          python cmake/make_versioncpp.py . CMake
      - name: Focal 20.04
        run: |
          bash .ci/script.sh focal
          bash .ci/deploy.sh focal
      - name: Groovy 20.10
        run: |
          bash .ci/script.sh groovy
          bash .ci/deploy.sh groovy
      - name: Hirsute 21.04
        run: |
          bash .ci/script.sh hirsute
          bash .ci/deploy.sh hirsute
